spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: user-analytics-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  datasource:
    url: jdbc:postgresql://localhost:5432/useranalyticsdb
    username: useranalytics
    password: secret
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update   # change to validate in prod
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
